version: '3'
services:
  postgres:
    container_name: postgres-container
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: university
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  spring-gradle:
    container_name: spring-container
    image: spring-gradle
    ports:
      - "27019:27019"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/university
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
